### ISSUE TITLE
Doesn't test data shouldn't be used while building the model?

### ISSUE THREAD

**Issue by idansc** [linanqiu/word2vec-sentiments#10]
A quote from the original paper:
"At test time, we freeze the vector representation for each
word, and learn the representations for the sentences using
gradient descent. Once the vector representations for the
test sentences are learned, we feed them through the logistic
regression to predict the movie rating."

shouldn't we use infer_vector instead? (which obviously drops the results)

**Comment by linanqiu** [comment]
That's a valid point!

That depends on how you want to go about doing your tests. Let's say you have 10,000 articles at hand. You can train the model on all 10,000, then only use 8,000 to train the classifier, then 2,000 to test the classifier. You can also train the model on 8,000, then use that to train the classifier. Then, any incremental change will be done using `infer_vector`.

The advantage of the first is that it gets you better results when you have a **fixed corpus**. The second allows for adding new articles (without retraining the whole model).

The problem I originally used this for was sentiment analysis of a given batch of data, so the first method was way more useful.
