### ISSUE TITLE
How to get label when input is a document?

### ISSUE THREAD

**Issue by quynguyen3490** [linanqiu/word2vec-sentiments#11]
Hello,
Very thank for tutorial! It's help me a lot.
I have a question, it's so new bie :)
After training, I have a document (sentence), I want get the label mapped to this document. But I don't know how to do this.
Can you show me how?
Thank u so much!

**Comment by linanqiu** [comment]
I did this using position of documents in the original array, but I'm sure you can modify the code to throw a few dictionaries in to enable that.
