### ISSUE TITLE
How to detect sentiment of text

### ISSUE THREAD

**Issue by GraphGrailAi** [linanqiu/word2vec-sentiments#12]
Could you provide example on how do i check text is it positive or negative?
Read http://linanqiu.github.io/2015/10/07/word2vec-sentiment/ and https://radimrehurek.com/gensim/models/word2vec.html
but there is no example.
I can do 

```
print(model.most_similar('good')) 
print(model.most_similar('terrible'))
print(model.most_similar(positive=['woman', 'king'], negative=['man']))
```

output is fine. What is the syntax to get "pos" or "neg" result?

**Comment by rxng** [comment]
any answer for this?

**Comment by linanqiu** [comment]
The labels (for both test and train) should tell you which ones are positive and negative.
