### ISSUE TITLE
ipynb file seems to be invalid

### ISSUE THREAD

**Issue by RenatoPerotti** [linanqiu/word2vec-sentiments#15]
Github does not load the word2vec-sentiment.ipynb file, I suppose it is corrupt, can you upload a fresh one!?
Thanx for the update on the new gensim by the way, and I'm looking forward to do the tutorial!
Cheers, RP

**Comment by john-bhat** [comment]
jupyter  notebook is giving error while opening word2vec-sentiment .ipynb file ..please fix it


Error:
nreadable Notebook: C:\Users\admin\Documents\word2vec-sentiment.ipynb NotJSONError("Notebook does not appear to be JSON: u'\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lan...",)

**Comment by linanqiu** [comment]
Fixed the ipynb. Thanks
