### ISSUE TITLE
sentences_perm() impose randomness while calculating accuracies

### ISSUE THREAD

**Issue by avinashsai** [linanqiu/word2vec-sentiments#23]
Due to shuffling of sentences in class "TaggedLineSentence" in every epoch, the vectors produced by training model in two subsequent runs are different which leads to randomness in accuracy when trained and tested with classifiers.

**Comment by linanqiu** [comment]
Yes but I'm not sure how that's a problem?

**Comment by avinashsai** [comment]
When the classifiers are trained and tested in the first run it shows 86% and in the second run it shows 83%.
Hence there is a deviation of 3% for the same model, which doesn't guarantee reliability of the model.
