### ISSUE TITLE
Bad results

### ISSUE THREAD

**Issue by MarcosGrzeca** [linanqiu/word2vec-sentiments#27]
We run exactly this source code https://linanqiu.github.io/2015/10/07/word2vec-sentiment/ and the result was 57%.

Follow the link to source code:
https://github.com/MarcosGrzeca/hatedetector/blob/master/tweets/outro.py

**Comment by linanqiu** [comment]
Can you run the latest code from GitHub?

**Comment by linanqiu** [comment]
I mean from the repository itself

**Comment by MarcosGrzeca** [comment]
Yes, but how can I use all Doc2Vec training data?

**Comment by MarcosGrzeca** [comment]
I tryed run the last version python3 word2vec-sentiments.py

The output log:

```
2019-10-17 00:56:45,756 - root - INFO - Fitting
/var/www/html/word2vec-sentiments/venv/lib/python3.5/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
2019-10-17 00:57:04,366 - root - INFO - 0.25132
```

**Comment by MarcosGrzeca** [comment]
I don't understand how the result can be so bad. I'm doing something wrong. Can you help?

**Comment by linanqiu** [comment]
I'm sorry I don't think that's enough information for me to help.

**Comment by MarcosGrzeca** [comment]
What information do you need?

I run python3 word2vec-sentiments.py and the result was very poor.

Thank you

**Comment by linanqiu** [comment]
Unfortunately I don’t have the time to rerun and verify this right now.

**Comment by linanqiu** [comment]
Can you do some basic debugging? Check if you’re getting the right vector
embeddings. Check if the training data and testing data are correct.
There’s a lot more you can do besides telling me that one number at the end
is wrong.

**Comment by MarcosGrzeca** [comment]
Thanks for the response.

Unfortunately I have no knowledge in python, but I will try to debug.
