### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'tags'

### ISSUE THREAD

**Issue by namp** [linanqiu/word2vec-sentiments#3]
Tried to run the code and I'm getting the following error as soon as the call to train is invoked:
model.train(sentences.sentences_perm())

File "/Users/nikos/anaconda/lib/python2.7/site-packages/gensim/models/doc2vec.py", line 638, in _do_train_job
    indexed_doctags = self.docvecs.indexed_doctags(doc.tags)
AttributeError: 'numpy.ndarray' object has no attribute 'tags'

My installation is as follows:

OSX Yosemite 10.10.5

Python 2.7.10 :: Anaconda 2.3.0 (x86_64) 

gensim==0.12.1
scipy==0.15.1
numpy==1.9.2

**Comment by namp** [comment]
The problem is that the call to the method "sentences_perm" destroys the attributes of the LabeledSentence (in the resulting numpy array)

A workaround that works is as follows:

sentences_list=sentences.to_array()
Idx=range(len(sentences_list))

for epoch in range(10):
    shuffle(Idx)
    perm_sentences = [sentences_list[i] for i in Idx]
    model.train(perm_sentences)

**Comment by linanqiu** [comment]
Reverted a pull request @scottyli made that. Try that?

**Comment by namp** [comment]
Seems that I rediscovered the wheel :P  Indeed, that works

Thanks
