### ISSUE TITLE
Error when inspecting the model

### ISSUE THREAD

**Issue by silentBug** [linanqiu/word2vec-sentiments#5]
@linanqiu So, when I run this:
model['TRAIN_NEG_0']

I get this error:
 File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 1204, in **getitem**
    return self.syn0[self.vocab[words].index]
KeyError: 'TRAIN_NEG_0'

I also get the same error when I'm training vectors i.e.
train_arrays[i] = model[prefix_train_pos]
## 

MacOS 10.10.4
python 2.7.6
gensim 0.12.1
numpy 1.9.2

**Comment by linanqiu** [comment]
It seems like you haven't trained the model yet...

**Comment by silentBug** [comment]
@linanqiu I think I have. Here is what I did:

 CODE:
:
:
print('training...')
sentences_list=sentences.to_array()
Idx=range(len(sentences_list))

for epoch in range(10):

> > random.shuffle(Idx)
> > perm_sentences = [sentences_list[i] for i in Idx]
> > model.train(perm_sentences)

print(model.most_similar('good'))
print(model['TRAIN_NEG_0'])

OUTPUT:

training...
[(u'great', 0.8698725700378418), (u'decent', 0.8210494518280029), (u'nice', 0.8178964257240295), (u'fine', 0.804987907409668), (u'bad', 0.8049429059028625), (u'excellent', 0.7895264625549316), (u'cool', 0.7774388790130615), (u'terrific', 0.7675904035568237), (u'solid', 0.7479405999183655), (u'ok', 0.7392432689666748)]
Traceback (most recent call last):
  File "/.../0_experiment/word2vec/w2v.py", line 62, in <module>
    print(model['TRAIN_NEG_0'])
  File "/Library/Python/2.7/site-packages/gensim/models/word2vec.py", line 1204, in **getitem**
    return self.syn0[self.vocab[words].index]
KeyError: 'TRAIN_NEG_0'

**Comment by silentBug** [comment]
@linanqiu it seems that there is a compatibility problem of some sort. Everything works like a charm once I rolled back to gensim 0.10.~

but I'm not sure whether all those who have 0.12.- have the same issue. if so this needs to be looked into :)

**Comment by linanqiu** [comment]
Hey sorry for the lack of response. I'll update this when I have time :(

**Comment by shellyjang** [comment]
I had the same problem - did some digging around the gensim doc and found that you can fix the problem by adding .docvecs

model.docvecs['TRAIN_NEG_0'] 

will give you the same result, and the rest of the code in the tutorial runs.

**Comment by linanqiu** [comment]
Awesome! Will add that when I’m free later this week. Thanks so much!
