### ISSUE TITLE
KeyError: 'TRAIN_NEG_0'

### ISSUE THREAD

**Issue by ahleeny** [linanqiu/word2vec-sentiments#7]
Hi,

Thanks for your detailed explanation!
I've tried out your code but encountered some errors.. 

Example of my sentence:
LabeledSentence([u'I', u'went', u'to', u'the', u'restaurant', u'the', u'other', u'day', u'with', u'family.', u'The', u'food', u'was', u'tasteless,', u'the', u'service', u'was', u'really', u'slow', u'and', u'the', u'Italian', u'guy', u'very', u'rude.', u'Not', u'sure', u'why', u'people', u'even', u'bother', u'to', u'dine', u'there.', u'Not', u'going', u'again', u'for', u'sure'], ['TRAIN_NEG_1'])

After training, I tried testing out the model using

> > > model['TRAIN_NEG_0']
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Users/administrator/anaconda/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1259, in **getitem**
> > >     return self.syn0[self.vocab[words].index]
> > > KeyError: 'TRAIN_NEG_0'

May I ask if there is any resolution? >_<

**Comment by yordogan** [comment]
see issue #5, instead of `model['TRAIN_NEG_0']` write `model.docvecs['TRAIN_NEG_0']`

**Comment by linanqiu** [comment]
Yup added that into the comments
