### ISSUE TITLE
How could I apply the code for multiple classes classification

### ISSUE THREAD

**Issue by vinhqdang** [linanqiu/word2vec-sentiments#8]
Hi 

First of all thank you very much for your great tutorial.

You showed how to use doc2vec to classify 2 classes of text. How should I apply this technique if I have more than2 classes?

Thanks,

**Comment by idimitriadis** [comment]
I would like to thank you too for your valuable contribution with this tutorial... Helped me a lot! 
As @vinhqdang already mentioned, i face the same problem, so your help would be much appreciated!
Maybe if we initialized the arrays with NaN?

**Comment by linanqiu** [comment]
So multiclass classification with SVM is inherently problematic. You may very well end up with stuff like this

![http://courses.media.mit.edu/2006fall/mas622j/Projects/aisen-project/boaa-diagram.png](http://courses.media.mit.edu/2006fall/mas622j/Projects/aisen-project/boaa-diagram.png)

If you have to do so, you won't be able to use a regression (that gives you a range of values from 0 to 1). Instead you'll probably have to use a classification (that on 2 classes give you either 0 or 1, or on 3 classes give you 0 1 or 2). scikit-learn's svm provides multiclass support, but like mentioned earlier it is problematic.
